[".vim/pack/bundles/start/syntastic"]
    type = "archive"
    url = "https://github.com/vim-syntastic/syntastic/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/pack/airblade/start/vim-gitgutter"]
    type = "archive"
    url = "https://github.com/airblade/vim-gitgutter/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
